#!/bin/python3

def split_and_join(line):
    line = line.split(" ")
    a = "-".join(line)
    return a

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)
