#!/bin/python3

if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()
    list = (student_marks[query_name])
    sum = sum(list)
    average = sum/len(list)
    answer = format(average, '.2f')
    print(answer)
